# NUMPY Practice

In [1]:
import numpy as np

In [2]:
numpy_A = np.array([
    [1,3],[4,5],[6,4]
])
numpy_A

array([[1, 3],
       [4, 5],
       [6, 4]])

In [5]:
print(numpy_A.size)
print(numpy_A.shape)
print(numpy_A.ndim)
print(numpy_A.dtype)
print(numpy_A.itemsize)
print(numpy_A.shape[0])
print(numpy_A.shape[-1])
print(numpy_A)

6
(3, 2)
2
int32
4
3
2
[[1 3]
 [4 5]
 [6 4]]


In [7]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.empty((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.empty_like((2,4))

array([669682160,       492])

In [13]:
np.random.randint((2,4))

array([1, 0])

In [14]:
np.random.random_sample((2,4))

array([[0.23652613, 0.86851636, 0.72356076, 0.1751071 ],
       [0.88535192, 0.07327391, 0.1816864 , 0.20098943]])

In [15]:
print(numpy_A.nbytes)

24


In [20]:
np.full((2,4), 99)

array([[99, 99, 99, 99],
       [99, 99, 99, 99]])

In [21]:
np.full_like((2,4),99)

array([99, 99])

In [23]:
np.arange(2,54)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52,
       53])

In [25]:
np.linspace(2,4)

array([2.        , 2.04081633, 2.08163265, 2.12244898, 2.16326531,
       2.20408163, 2.24489796, 2.28571429, 2.32653061, 2.36734694,
       2.40816327, 2.44897959, 2.48979592, 2.53061224, 2.57142857,
       2.6122449 , 2.65306122, 2.69387755, 2.73469388, 2.7755102 ,
       2.81632653, 2.85714286, 2.89795918, 2.93877551, 2.97959184,
       3.02040816, 3.06122449, 3.10204082, 3.14285714, 3.18367347,
       3.2244898 , 3.26530612, 3.30612245, 3.34693878, 3.3877551 ,
       3.42857143, 3.46938776, 3.51020408, 3.55102041, 3.59183673,
       3.63265306, 3.67346939, 3.71428571, 3.75510204, 3.79591837,
       3.83673469, 3.87755102, 3.91836735, 3.95918367, 4.        ])

In [29]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
asd=np.identity(42)

In [32]:
asd

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [33]:
asd.ravel()

array([1., 0., 0., ..., 0., 0., 1.])

In [43]:
matrix= np.array([
    [1,3],[5,3],[6,3]
])
matrix

array([[1, 3],
       [5, 3],
       [6, 3]])

In [44]:
matrix2= np.array([
    [1,3],[5,3],[6,2]
])
matrix2

array([[1, 3],
       [5, 3],
       [6, 2]])

In [47]:
np.sum(matrix, axis=0)

array([12,  9])

In [48]:
np.sum(matrix,axis=1)

array([4, 8, 9])

In [49]:
np.sum(matrix2,axis=1)

array([4, 8, 8])

In [50]:
np.sum(matrix2, axis=0)

array([12,  8])

In [51]:
numpy_A

array([[1, 3],
       [4, 5],
       [6, 4]])

In [52]:
numpy_A.T

array([[1, 4, 6],
       [3, 5, 4]])

In [53]:
numpy_A.shape

(3, 2)

In [54]:
numpy_A.reshape(2,3)

array([[1, 3, 4],
       [5, 6, 4]])

In [55]:
numpy_A.reshape(6)

array([1, 3, 4, 5, 6, 4])

In [56]:
numpy_A.flat

In [58]:
for item in numpy_A.flat:
    print(item)

1
3
4
5
6
4


In [60]:
print(numpy_A.argmax())
print(numpy_A.argmin())
print(numpy_A.argsort())


4
0
[[0 1]
 [0 1]
 [1 0]]


In [72]:
print(np.sum(numpy_A))
print(np.max(numpy_A))
print(np.min(numpy_A))
print(np.mean(numpy_A))
print(np.sqrt(numpy_A))

23
6
1
3.8333333333333335
[[1.         1.73205081]
 [2.         2.23606798]
 [2.44948974 2.        ]]


In [73]:
numpy_A

array([[1, 3],
       [4, 5],
       [6, 4]])

In [75]:
np.where(numpy_A<5)

(array([0, 0, 1, 2], dtype=int64), array([0, 1, 0, 1], dtype=int64))

In [78]:
np.count_nonzero(numpy_A)

6

# Task 

In [80]:
output = np.ones((5,5))
output

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [85]:
z = np.zeros((3,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [86]:
z[1,1] = 9
z

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [87]:
output[1:-1,1:-1] = z

In [88]:
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [89]:
numpy_A

array([[1, 3],
       [4, 5],
       [6, 4]])

In [92]:
matrix = ([
    [1,2],[6,4]
])

In [93]:
np.linalg.det(matrix)

-8.000000000000002

In [95]:
np.sin(matrix)

array([[ 0.84147098,  0.90929743],
       [-0.2794155 , -0.7568025 ]])

In [96]:
np.cos(matrix)

array([[ 0.54030231, -0.41614684],
       [ 0.96017029, -0.65364362]])

In [97]:
np.tan(matrix)

array([[ 1.55740772, -2.18503986],
       [-0.29100619,  1.15782128]])

In [98]:
v1 = np.array([
    [1,4],[5,5],[6,3]
])
v1

array([[1, 4],
       [5, 5],
       [6, 3]])

In [99]:
v2 = np.array([
    [4,2],[5,2],[6,7]
])
v2

array([[4, 2],
       [5, 2],
       [6, 7]])

In [104]:
np.vstack([v1,v2])


array([[1, 4],
       [5, 5],
       [6, 3],
       [4, 2],
       [5, 2],
       [6, 7]])

In [105]:
np.hstack([v1,v2])

array([[1, 4, 4, 2],
       [5, 5, 5, 2],
       [6, 3, 6, 7]])

In [106]:
numpy_A

array([[1, 3],
       [4, 5],
       [6, 4]])

In [107]:
numpy_A[1:]

array([[4, 5],
       [6, 4]])

In [110]:
numpy_A[:,1]

array([3, 5, 4])

In [111]:
numpy_A.ravel()

array([1, 3, 4, 5, 6, 4])

In [116]:
matrix2= [2,34,53,2,32,3,24,24,2,42,4,2,31,24,2]

In [117]:
matrix2

[2, 34, 53, 2, 32, 3, 24, 24, 2, 42, 4, 2, 31, 24, 2]

In [118]:
matrix2[2:10:4]

[53, 24]