# Numpy_Practices

In [1]:
import numpy as np

In [2]:
print('Hello World')

Hello World


In [3]:
numpy_A = np.arange(1,23,dtype=np.float32)

In [4]:
numpy_A

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22.], dtype=float32)

In [5]:
myarr = np.array([
    [10,6],[5,2],[4,2]
])
myarr

array([[10,  6],
       [ 5,  2],
       [ 4,  2]])

In [6]:
myarr.shape

(3, 2)

In [7]:
myarr.ndim

2

In [8]:
myarr.dtype

dtype('int32')

In [9]:
myarr.size

6

In [10]:
myarr.shape[0]

3

In [ ]:
myarr.shape[-1]

2

In [15]:
zeros = np.zeros((1,4))
zeros

array([[0., 0., 0., 0.]])

In [17]:
ones = np.ones((1,4))
ones

array([[1., 1., 1., 1.]])

In [18]:
rng = np.arange(1,30)
rng

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [23]:
lspace = np.linspace(1,3,8)
lspace

array([1.        , 1.28571429, 1.57142857, 1.85714286, 2.14285714,
       2.42857143, 2.71428571, 3.        ])

In [24]:
numpy_B = np.array([
    [1,4],[4,5],[4,6]
])
numpy_B

array([[1, 4],
       [4, 5],
       [4, 6]])

In [25]:
numpy_B.dtype

dtype('int32')

In [26]:
numpy_B.size

6

In [27]:
numpy_B.ndim

2

In [28]:
numpy_B.shape

(3, 2)

In [30]:
numpy_B.shape[1]

2

In [31]:
numpy_B.shape[0]

3

In [32]:
numpy_B.shape[-1]

2

In [36]:
numpy_B = np.arange(1,20)

numpy_B

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [37]:
numpy_B = np.linspace(1,10,20)
numpy_B

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [39]:
numpy_B = np.zeros((1,10))
numpy_B

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [40]:
numpy_B = np.ones((1,10))
numpy_B

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [42]:
emp = np.empty((5,4))
emp

array([[ 1.        ,  1.47368421,  1.94736842,  2.42105263],
       [ 2.89473684,  3.36842105,  3.84210526,  4.31578947],
       [ 4.78947368,  5.26315789,  5.73684211,  6.21052632],
       [ 6.68421053,  7.15789474,  7.63157895,  8.10526316],
       [ 8.57894737,  9.05263158,  9.52631579, 10.        ]])

In [44]:
emp_like = np.empty_like(numpy_B)
emp_like

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [46]:
ide = np.identity(52)
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [47]:
numpy_B.shape

(1, 10)

In [48]:
numpy_B

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [49]:
numpy_B.reshape(5,2)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [50]:
numpy_B.reshape(2,5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [52]:
numpy_B.ravel()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [53]:
numpy_C = np.array([
    [1,3],[4,2],[4,1],[4,5]
])
numpy_C

array([[1, 3],
       [4, 2],
       [4, 1],
       [4, 5]])

In [54]:
print(numpy_C.dtype)
print(numpy_C.size)
print(numpy_C.shape)
print(numpy_C.ndim)
print(numpy_C.shape[0])
print(numpy_C.shape[1])
print(numpy_C.shape[-1])

int32
8
(4, 2)
2
4
2
2


In [55]:
np.arange(1,32)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [56]:
np.linspace(1,20,10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [57]:
np.zeros((1,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [58]:
np.ones((1,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [60]:
np.empty((1,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [61]:
np.empty_like(numpy_C)

array([[         0, 1072693248],
       [         0, 1072693248],
       [         0, 1072693248],
       [         0, 1072693248]])

In [62]:
numpy_C

array([[1, 3],
       [4, 2],
       [4, 1],
       [4, 5]])

In [63]:
numpy_C.shape

(4, 2)

In [64]:
numpy_C.reshape(8)

array([1, 3, 4, 2, 4, 1, 4, 5])

In [65]:
numpy_C.reshape(2,4)

array([[1, 3, 4, 2],
       [4, 1, 4, 5]])

In [66]:
numpy_C.ravel()

array([1, 3, 4, 2, 4, 1, 4, 5])

In [68]:
matrix_1= np.array([
    [1,2],[5,3],[1,4]
])
matrix_1

array([[1, 2],
       [5, 3],
       [1, 4]])

In [69]:
matrix_2  = np.array([
    [1,4],[6,3],[10,4]
])
matrix_2

array([[ 1,  4],
       [ 6,  3],
       [10,  4]])

In [75]:
np.sum(matrix_1, axis=0)

array([7, 9])

In [76]:
np.sum(matrix_2, axis=1)

array([ 5,  9, 14])

In [77]:
matrix_2.T

array([[ 1,  6, 10],
       [ 4,  3,  4]])

In [78]:
matrix_2.flat

In [79]:
for item in matrix_2.flat:
    print(matrix_2)

[[ 1  4]
 [ 6  3]
 [10  4]]
[[ 1  4]
 [ 6  3]
 [10  4]]
[[ 1  4]
 [ 6  3]
 [10  4]]
[[ 1  4]
 [ 6  3]
 [10  4]]
[[ 1  4]
 [ 6  3]
 [10  4]]
[[ 1  4]
 [ 6  3]
 [10  4]]


In [80]:
matrix

array([[1, 2],
       [5, 3],
       [1, 4]])

In [83]:
print(matrix.ndim)
print(matrix.nbytes)
print(matrix.shape)
print(matrix.shape[0])
print(matrix.shape[-1])
print(matrix.shape[1])
print(matrix.argmax())
print(matrix.argmin())
print(matrix.argsort())


2
24
(3, 2)
3
2
2
2
0
[[0 1]
 [1 0]
 [0 1]]


In [89]:
matrix = np.array([1,3,4,5,3])
matrix

array([1, 3, 4, 5, 3])

In [90]:
np.argmax(matrix)

3

In [91]:
np.argmin(matrix)

0

In [92]:
np.argsort(matrix)

array([0, 1, 4, 2, 3], dtype=int64)

In [93]:
np.add(matrix_1,matrix_2)

array([[ 2,  6],
       [11,  6],
       [11,  8]])

In [94]:
np.subtract(matrix_1,matrix_2)

array([[ 0, -2],
       [-1,  0],
       [-9,  0]])

In [95]:
np.multiply(matrix_1,matrix_2)

array([[ 1,  8],
       [30,  9],
       [10, 16]])

In [96]:
np.divide(matrix_1,matrix_2)

array([[1.        , 0.5       ],
       [0.83333333, 1.        ],
       [0.1       , 1.        ]])

In [99]:
np.count_nonzero(matrix)

5

In [101]:
np.where(matrix>5)

(array([], dtype=int64),)

In [102]:
matrix_2 = np.array([1,3,5,2,1,5])
matrix_2

array([1, 3, 5, 2, 1, 5])

In [105]:
np.where(matrix<=5)

(array([0, 1, 2, 3, 4], dtype=int64),)

In [106]:
matrix

array([1, 3, 4, 5, 3])