#  Numpy

In [1]:
import numpy as np

In [2]:
numpy_A = np.array([
    [2,4],[4,6],[8,5],[4,8],[4,2],[8,6]
])
numpy_A

array([[2, 4],
       [4, 6],
       [8, 5],
       [4, 8],
       [4, 2],
       [8, 6]])

In [4]:
print(numpy_A.ndim)
print(numpy_A.shape)
print(numpy_A.shape[0])
print(numpy_A.shape[1])
print(numpy_A.shape[-1])
print(numpy_A.nbytes)
print(numpy_A.dtype)
print(numpy_A.size)
print(numpy_A.itemsize)



2
(6, 2)
6
2
2
48
int32
12
4


In [7]:
np.empty((2,4))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 3.65608578e-321, 9.79107871e-307,
        8.34445561e-308]])

In [8]:
np.empty_like((2,4))

array([0, 0])

In [10]:
np.full((2,4), 44)

array([[44, 44, 44, 44],
       [44, 44, 44, 44]])

In [11]:
np.full_like((2,4),44)

array([44, 44])

In [12]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.arange(23,54)

array([23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
       40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53])

In [15]:
np.linspace(4,5)

array([4.        , 4.02040816, 4.04081633, 4.06122449, 4.08163265,
       4.10204082, 4.12244898, 4.14285714, 4.16326531, 4.18367347,
       4.20408163, 4.2244898 , 4.24489796, 4.26530612, 4.28571429,
       4.30612245, 4.32653061, 4.34693878, 4.36734694, 4.3877551 ,
       4.40816327, 4.42857143, 4.44897959, 4.46938776, 4.48979592,
       4.51020408, 4.53061224, 4.55102041, 4.57142857, 4.59183673,
       4.6122449 , 4.63265306, 4.65306122, 4.67346939, 4.69387755,
       4.71428571, 4.73469388, 4.75510204, 4.7755102 , 4.79591837,
       4.81632653, 4.83673469, 4.85714286, 4.87755102, 4.89795918,
       4.91836735, 4.93877551, 4.95918367, 4.97959184, 5.        ])

In [16]:
np.shape(numpy_A)

(6, 2)

In [18]:
numpy_A.reshape((3,4))

array([[2, 4, 4, 6],
       [8, 5, 4, 8],
       [4, 2, 8, 6]])

In [19]:
numpy_A.ravel()

array([2, 4, 4, 6, 8, 5, 4, 8, 4, 2, 8, 6])

In [20]:
numpy_A.shape

(6, 2)

In [21]:
numpy_A.sum(axis=0)

array([30, 31])

In [22]:
numpy_A.sum(axis=1)

array([ 6, 10, 13, 12,  6, 14])

In [23]:
numpy_A.flat

In [24]:
for item in numpy_A.flat:
    print(item)

2
4
4
6
8
5
4
8
4
2
8
6


In [26]:
np.min(numpy_A)

2

In [27]:
np.mean(numpy_A)


5.083333333333333

In [28]:
np.max(numpy_A)

8

In [29]:
np.argmin(numpy_A)

0

In [30]:
np.argmax(numpy_A)

4

In [31]:
np.argsort(numpy_A)

array([[0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0]], dtype=int64)

In [33]:
np.sqrt(numpy_A)

array([[1.41421356, 2.        ],
       [2.        , 2.44948974],
       [2.82842712, 2.23606798],
       [2.        , 2.82842712],
       [2.        , 1.41421356],
       [2.82842712, 2.44948974]])

In [34]:
np.random.randint(2,4)

3

In [35]:
np.random.random_sample((2,4))

array([[0.77961637, 0.70207045, 0.5998151 , 0.90355643],
       [0.67825851, 0.97412023, 0.08055402, 0.50649978]])

In [36]:
numpy_A

array([[2, 4],
       [4, 6],
       [8, 5],
       [4, 8],
       [4, 2],
       [8, 6]])

In [37]:
output = np.ones((5,5))

In [38]:
output

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
z= np.zeros((3,3))

In [41]:
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [46]:
z[1:-1] = 4 

In [47]:
z

array([[0., 0., 0.],
       [4., 4., 4.],
       [0., 0., 0.]])

In [48]:
output[1:-1,1:-1] = z

In [49]:
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 4., 4., 4., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [50]:
np.random.rand(2,4)

array([[0.26118928, 0.07584148, 0.54380187, 0.36850026],
       [0.47229314, 0.08322072, 0.10194518, 0.93724776]])

In [51]:
np.identity(32)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [52]:
numpy_A.repeat(5)

array([2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 6, 6, 6, 6, 8, 8,
       8, 8, 8, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 8, 8, 8, 8, 8, 4, 4, 4, 4,
       4, 2, 2, 2, 2, 2, 8, 8, 8, 8, 8, 6, 6, 6, 6, 6])

In [53]:
numpy_A.T

array([[2, 4, 8, 4, 4, 8],
       [4, 6, 5, 8, 2, 6]])

In [55]:
np.where(numpy_A<1)

(array([], dtype=int64), array([], dtype=int64))

In [56]:
np.where(numpy_A>3)

(array([0, 1, 1, 2, 2, 3, 3, 4, 5, 5], dtype=int64),
 array([1, 0, 1, 0, 1, 0, 1, 0, 0, 1], dtype=int64))

In [57]:
np.count_nonzero(numpy_A)

12

In [59]:
import sys
py_ar = [2,42,5,64,24]
np_ar = np.array(py_ar)
sys.getsizeof(1) * len(py_ar)

140

In [60]:
np_ar.itemsize * np_ar.size

20

In [62]:
np.cos(numpy_A)

array([[-0.41614684, -0.65364362],
       [-0.65364362,  0.96017029],
       [-0.14550003,  0.28366219],
       [-0.65364362, -0.14550003],
       [-0.65364362, -0.41614684],
       [-0.14550003,  0.96017029]])

In [63]:
np.sin(numpy_A)

array([[ 0.90929743, -0.7568025 ],
       [-0.7568025 , -0.2794155 ],
       [ 0.98935825, -0.95892427],
       [-0.7568025 ,  0.98935825],
       [-0.7568025 ,  0.90929743],
       [ 0.98935825, -0.2794155 ]])

In [67]:
np.tan(numpy_A)

array([[-2.18503986,  1.15782128],
       [ 1.15782128, -0.29100619],
       [-6.79971146, -3.38051501],
       [ 1.15782128, -6.79971146],
       [ 1.15782128, -2.18503986],
       [-6.79971146, -0.29100619]])

In [68]:
numpy_B = numpy_A

In [69]:
np.vstack([numpy_A,numpy_B])

array([[2, 4],
       [4, 6],
       [8, 5],
       [4, 8],
       [4, 2],
       [8, 6],
       [2, 4],
       [4, 6],
       [8, 5],
       [4, 8],
       [4, 2],
       [8, 6]])

In [70]:
np.hstack([numpy_A, numpy_B])

array([[2, 4, 2, 4],
       [4, 6, 4, 6],
       [8, 5, 8, 5],
       [4, 8, 4, 8],
       [4, 2, 4, 2],
       [8, 6, 8, 6]])

In [73]:
val = np.array([
    [3,4],[5,3]
])
val

array([[3, 4],
       [5, 3]])

In [74]:
np.linalg.det(val)

-11.000000000000002

In [75]:
data = np.genfromtxt('info.txt')

In [76]:
data

array([ 34.,  54.,  35.,  35.,  32., 532.,   5., 325.,   3.,  41.,   4.,
         3., 423.,  52.,   5., 225.,   2., 523.,   5.])

In [77]:
data  = np.genfromtxt('info.txt', delimiter=',')

In [79]:
data

array([ 34.,  54.,  35.,  35.,  32., 532.,   5., 325.,   3.,  41.,   4.,
         3., 423.,  52.,   5., 225.,   2., 523.,   5.])

In [80]:
data[:2]

array([34., 54.])

In [81]:
data[2:]

array([ 35.,  35.,  32., 532.,   5., 325.,   3.,  41.,   4.,   3., 423.,
        52.,   5., 225.,   2., 523.,   5.])