In [ ]:
import numpy as np

In [3]:
numpy_A = np.array([
    [1,4],[5,3],[4,1],[3,5],[2,5]
])
numpy_A

array([[1, 4],
       [5, 3],
       [4, 1],
       [3, 5],
       [2, 5]])

In [4]:
print(numpy_A.dtype)
print(numpy_A.ndim)
print(numpy_A.size)
print(numpy_A.shape)
print(numpy_A.shape[0])
print(numpy_A.shape[1])
print(numpy_A.shape[-1])

int32
2
10
(5, 2)
5
2
2


In [5]:
np.zeros((1,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
np.ones((1,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [7]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [8]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [9]:
np.empty((1,10))

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [10]:
np.empty_like(numpy_A)

array([[         0,          1],
       [         0,  757538860],
       [       756,          0],
       [       768,        589],
       [ 657272103, 1044253225]])

In [11]:
numpy_A.shape

(5, 2)

In [12]:
numpy_A.reshape(10)

array([1, 4, 5, 3, 4, 1, 3, 5, 2, 5])

In [13]:
numpy_A.reshape(2,5)

array([[1, 4, 5, 3, 4],
       [1, 3, 5, 2, 5]])

In [14]:
numpy_A.reshape(1,10)

array([[1, 4, 5, 3, 4, 1, 3, 5, 2, 5]])

In [15]:
numpy_A.ravel()

array([1, 4, 5, 3, 4, 1, 3, 5, 2, 5])

In [16]:
numpy_A.T

array([[1, 5, 4, 3, 2],
       [4, 3, 1, 5, 5]])

In [17]:
numpy_A.flat

In [25]:
np.sum(numpy_A, axis=1)

array([5, 8, 5, 8, 7])

In [26]:
np.sum(numpy_A, axis=0)

array([15, 18])

In [27]:
np.max(numpy_A)

5

In [28]:
np.min(numpy_A)

1

In [29]:
np.sqrt(numpy_A)

array([[1.        , 2.        ],
       [2.23606798, 1.73205081],
       [2.        , 1.        ],
       [1.73205081, 2.23606798],
       [1.41421356, 2.23606798]])

In [30]:
numpy_A.nbytes

40

In [31]:
numpy_A.ndim

2

In [32]:
numpy_A.shape

(5, 2)

In [33]:
numpy_A.shape[0]

5

In [34]:
numpy_A.shape[1]

2

In [35]:
numpy_A.shape[-1]

2

In [37]:
numpy_A.shape[1]

2

In [39]:
np.mean(numpy_A)

3.3

In [41]:
np.add(10, numpy_A)

array([[11, 14],
       [15, 13],
       [14, 11],
       [13, 15],
       [12, 15]])

In [48]:
np.nonzero(numpy_A)

(array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4], dtype=int64),
 array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int64))

In [49]:
import sys
py_ar = [0,4,5,5,2]
np_ar = np.array(py_ar)
sys.getsizeof(1)*len(py_ar)

140

In [50]:
np_ar.itemsize * np_ar.size

20