# NUMPY_Practice

In [1]:
import numpy as np

In [2]:
numpy_A = np.array([
    [1,3],[5,6],[7,4],[6,4]
])
numpy_A

array([[1, 3],
       [5, 6],
       [7, 4],
       [6, 4]])

In [4]:
print(numpy_A.size)
print(numpy_A.itemsize)
print(numpy_A.shape)
print(numpy_A.dtype)
print(numpy_A.ndim)
print(numpy_A.shape[0])
print(numpy_A.shape[-1])
print(numpy_A.shape[1])
print(numpy_A.nbytes)

8
4
(4, 2)
int32
2
4
2
2
32


In [5]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.full((2,4),99 )

array([[99, 99, 99, 99],
       [99, 99, 99, 99]])

In [9]:
np.full_like((2,4),99)

array([99, 99])

In [10]:
np.empty((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.empty_like((2,3))

array([0, 0])

In [13]:
np.random.random_sample((2,4))

array([[0.48058407, 0.06972072, 0.01706139, 0.10730033],
       [0.27257784, 0.09047019, 0.64668609, 0.23355879]])

In [14]:
np.random.randint((2,4))

array([0, 0])

In [16]:
np.arange(2,5)

array([2, 3, 4])

In [17]:
np.linspace(2,45,8)

array([ 2.        ,  8.14285714, 14.28571429, 20.42857143, 26.57142857,
       32.71428571, 38.85714286, 45.        ])

In [19]:
np.random.rand(24,53)

array([[0.30180617, 0.85497549, 0.14327461, ..., 0.06087834, 0.47722536,
        0.86543288],
       [0.47475293, 0.84803126, 0.1386619 , ..., 0.95592234, 0.60374991,
        0.34203493],
       [0.75387834, 0.39584316, 0.62160071, ..., 0.1626924 , 0.01412561,
        0.41270911],
       ...,
       [0.99187284, 0.81016106, 0.0205173 , ..., 0.13018063, 0.47171678,
        0.47582588],
       [0.8802302 , 0.07074406, 0.03189765, ..., 0.07320701, 0.76171101,
        0.46666977],
       [0.14845252, 0.61431689, 0.81940088, ..., 0.67631248, 0.17422034,
        0.47369512]])

In [20]:
np.identity(423)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [22]:
np.random.randint((4,5))

array([2, 2])

In [23]:
numpy_A

array([[1, 3],
       [5, 6],
       [7, 4],
       [6, 4]])

In [24]:
numpy_A.shape

(4, 2)

In [25]:
numpy_A.reshape((2,4))

array([[1, 3, 5, 6],
       [7, 4, 6, 4]])

In [26]:
numpy_A.ravel()

array([1, 3, 5, 6, 7, 4, 6, 4])

In [27]:
numpy_A.T

array([[1, 5, 7, 6],
       [3, 6, 4, 4]])

In [28]:
numpy_A.sum(axis=0)

array([19, 17])

In [29]:
numpy_A.sum(axis=1)

array([ 4, 11, 11, 10])

In [31]:
numpy_A.flat

In [32]:
for item in numpy_A.flat:
    print(item)

1
3
5
6
7
4
6
4


In [33]:
numpy_A.argmax()

4

In [34]:
numpy_A.argmin()

0

In [35]:
numpy_A.argsort()


array([[0, 1],
       [0, 1],
       [1, 0],
       [1, 0]], dtype=int64)

In [36]:
numpy_A.sum()

36

In [39]:
print(numpy_A.sum())
print(numpy_A.min())
print(numpy_A.max())
print(numpy_A.mean())
      

36
1
7
4.5


In [41]:
np.count_nonzero(numpy_A)

8

In [43]:
np.sum(numpy_A)

36

In [44]:
np.sqrt(numpy_A)

array([[1.        , 1.73205081],
       [2.23606798, 2.44948974],
       [2.64575131, 2.        ],
       [2.44948974, 2.        ]])

In [45]:
np.std(numpy_A)

1.8027756377319946

In [48]:
import sys
py_ar = [0,4,5,5,2]
np_ar = np.array(py_ar)
sys.getsizeof(1) * len(py_ar)

140

In [49]:
np_ar.itemsize * np_ar.size

20

In [50]:
output = np.ones((5,5))

In [51]:
output

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [52]:
z = np.zeros((3,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [55]:
z[2,-2 ] = 9

In [56]:
z

array([[0., 0., 0.],
       [0., 0., 9.],
       [0., 9., 0.]])

In [57]:
z

array([[0., 0., 0.],
       [0., 0., 9.],
       [0., 9., 0.]])

In [58]:
output[1:-1,1:-1] = z

In [59]:
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 9., 1.],
       [1., 0., 9., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [60]:
np.sin(numpy_A)

array([[ 0.84147098,  0.14112001],
       [-0.95892427, -0.2794155 ],
       [ 0.6569866 , -0.7568025 ],
       [-0.2794155 , -0.7568025 ]])

In [61]:
np.cos(numpy_A)

array([[ 0.54030231, -0.9899925 ],
       [ 0.28366219,  0.96017029],
       [ 0.75390225, -0.65364362],
       [ 0.96017029, -0.65364362]])

In [62]:
np.tan(numpy_A)

array([[ 1.55740772, -0.14254654],
       [-3.38051501, -0.29100619],
       [ 0.87144798,  1.15782128],
       [-0.29100619,  1.15782128]])

In [67]:
z = ([342,3,432,42,5,45,45,43,634,63,63,6,36,34,6,3446,3446,346])


In [70]:
v1 =np.array([
    [2,4],[6,5],[6,3]
])
v1

array([[2, 4],
       [6, 5],
       [6, 3]])

In [72]:
v2 = np.array([
    [5,7],[7,4],[2,3]
])
v2

array([[5, 7],
       [7, 4],
       [2, 3]])

In [74]:
np.vstack([v1,v2])

array([[2, 4],
       [6, 5],
       [6, 3],
       [5, 7],
       [7, 4],
       [2, 3]])

In [75]:
np.hstack([v1,v2])

array([[2, 4, 5, 7],
       [6, 5, 7, 4],
       [6, 3, 2, 3]])

In [78]:
np.ravel([v1,v2])

array([2, 4, 6, 5, 6, 3, 5, 7, 7, 4, 2, 3])

In [79]:
numpy_A

array([[1, 3],
       [5, 6],
       [7, 4],
       [6, 4]])

In [81]:
numpy_A[:2]

array([[1, 3],
       [5, 6]])

In [82]:
numpy_A[1:]

array([[5, 6],
       [7, 4],
       [6, 4]])

# And The Journey Begins